### ISSUE TITLE
con.php

### ISSUE THREAD

**Issue by shmorgan** [KoljaWindeler/macs#1]
I would suggest renaming the file con.php. While odd, windows does not allow this file name in the system, and when I unziped the archive, this file was not restored due to restrictions in Windows 10.

Would suggest renaming to something without con in the name.

**Comment by KoljaWindeler** [comment]
Works here on windows 10

**Comment by shmorgan** [comment]
Humm, Strange, We tested this on several different computers, when you try to copy the file to the windows 10 operating system or unzip the file containing this file, you get an error on this file name. A quick google of the error message bring up a restriction of file names with con in the beginning of the file name. Conflicts with the reserved con device name for the Console.

**Comment by KoljaWindeler** [comment]
ha i've added it to my windows partition while booting ubuntu and windows never complained .. but have a look .. I've just pushed a fix for you

**Comment by shmorgan** [comment]
Any chance I could get you direct email address?Thanks,Stephen MorganHome: 770-237-8337Cell: 770-633-6007

-------- Original Message --------
Subject: Re: [KoljaWindeler/macs] con.php (#1)
